### ISSUE TITLE
Bremen Hbf <-> Hannover Hbf via Verden (Aller)

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#12]
Streckennummer 1700
Wunstorf (km 21,4) - Hannover Hbf (km 0,0)

**Comment by christophstoeber** [comment]
Streckennummer 1740
Bremen Hbf (km 122,2) - Wunstorf (km 21,4)

Streckennummer 1700
Wunstorf (km 21,4) - Hannover Hbf (km 0,0)
