### ISSUE TITLE
Erfurt Hbf <-> Leipzig Hbf via Schnellfahrstrecke

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#2]
Streckennummer 5919
Erfurt Hbf (km 191,078) - Leipzig Hbf (km 311,896)

**Comment by christophstoeber** [comment]
Streckennummer 5919
Erfurt Hbf (km 191,078) - Leipzig Hbf (km 311,896)

Seihe [Karte von DB Netz](https://geovdbn.deutschebahn.com/isr)
