### ISSUE TITLE
Hamburg-Altona<-> Kiel Hbf via Neumünster

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#23]
Streckennummer 1220
Hamburg-Altona (km 0,7) - Kiel Hbf (km 105,5)

Strecke zur Verbindungsbahn (Hamburg Dammtor, Hamburg Hf)
Streckennummer 1232
Hamburg Rainweg (km 1,4) - Hamburg-Langenfelde Bbf (km 4,1)

**Comment by christophstoeber** [comment]
Streckennummer 1220
Hamburg-Altona (km 0,7) - Kiel Hbf (km 105,5)
