### ISSUE TITLE
Berlin Ostbahnhof <-> Hannover Hbf via Wolfsburg

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#3]
Streckennummer 1730
Hannover Hbf (km 0,0) - Lehrte (km16,1)

Streckennummer 6107
Lehrte (km 239,3) - Oebisfelde (km 167,3)

Streckennummer 6185
Oebisfelde (km 267,9) - Berlin-Spandau (km 112,7)

Streckennummer 6109
Berlin-Spandau (km 18,3) - Berlin Ostbahnhof (0,0)

Abzweig nach Stendal
Streckennummer 6107
Stendal (km 105,1) <-> Nahrstedt (km 115,5)

Stendal <-> Rathenow (Schnellfahrstrecke) siehe #5

**Comment by christophstoeber** [comment]
Streckennummer 1730
