### ISSUE TITLE
Berlin <-> Halle via Schnellfahrstrecke

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#31]
Streckennummer 6171
Berlin Hbf (km 0,0) - Berlin Südkreuz Süd Abzw (km 9,0)

Streckennummer 6132
Berlin Südkreuz Süd Abzw (km 4,3) - Halle (Saale) Hbf (km 161,6)

**Comment by christophstoeber** [comment]
Streckennummer 6171
Berlin Hbf (km 0,0) - Berlin Südkreuz Süd Abzw (km 9,0)

Streckennummer 6132
Berlin Südkreuz Süd Abzw (km 4,3) - Halle (Saale) Hbf (km 161,6)
