### ISSUE TITLE
Berlin <-> Dresden via Elsterwerda und Dresden Hbf <-> Radebeul Abzw Az via Dresden-Friedrichstadt

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#33]
[Streckennummer 6109
Berlin Hbf (km 5,4) - Berlin Ostbahnhof (km 0,0)
Streckennummer 6153
Berlin Ostbahnhof (km 0,0) - Berlin Ostendgestell (km 8,7)]

Streckennummer 6150
Berlin Ostendgestell (km 0,0) - StrUeb_6080_6150 (km 1,0)

Streckennumer 6080
StrUeb_6080_6150 (km 25,8) - Berlin Eichgestell (km 25,0)

Streckennummer 6126
Berlin Eichgestell (km 44,1) - Glasower Damm Ost (km 27,1)

Streckennummer 6138
Glasower Damm Ost (km 17,2) - Glasower Damm Süd (km 19,2)

Streckennumer 6135
Glasower Damm Süd (km 18,9) - Elsterwerda Streckenwechsel 6135/6248 (km 124,5)

Streckennummer 6248
Elsterwerda Streckenwechsel 6135/6248 (km 50,3) - Radebeul Abzw Az (km 12,0)

Streckennummer 6251
Radebeul Abzw Az (km 0,0) - Radebeul Nord (km 1,9)

weiter von/nach Dresden via Dresden-Neustadt siehe #17

**Comment by christophstoeber** [comment]
Streckennummer 6109
Berlin Hbf (km 5,4) - Berlin Ostbahnhof (km 0,0)

Streckennummer 6153
Berlin Ostbahnhof (km 0,0) -  Abzw Berlin Ostendgestell (km 8,7)

Streckennummer 6150
Berlin Ostendgestell (km 0,0)  - StrUeb_6080_6150 (km 1,0)

Streckennumer 6080
StrUeb_6080_6150 (km 25,8) - StrUeb_6080_6148 (km 25,7)
StrUeb_6080_6148 (km 25,7) - Berlin Eichgestell (km 25,0)

Streckennummer 6126
Berlin Eichgestell (km 44,1) - Berlin Wendenheide (km 42,7)
Berlin Wendenheide (km 42,7) - Grünauer Kreuz Nord (km 40,7)
Grünauer Kreuz Nord (km 40,7) - Grünauer Kreuz Süd (km 39,5)
Grünauer Kreuz Süd (km 39,5) - Abzw Glasower Damm Ost (km 28,1)

Streckennummer 6138
Glasower Damm Ost (km 17,2) - Glasower Damm Süd (km 19,2)

Streckennumer 6135
Glasower Damm Süd (km 18,9) - Blankenfelde (Kr Teltow-Fläming) (km 19,5)

Streckennummer 6135 / 6248
Blankenfelde (Kr Teltow-Fläming) (km 19,4) - Elsterwerda (km 122,8)

Weiter ab Elsterwerda?

**Comment by ChristophsAcc** [comment]
Strecke via Dresden-Friedrichstadt

Streckennummer 6248
Radebeul Abzw Az (km 12,0) - Dresden-Friedrichstadt (km 0,2)

Streckennummer 6244
Dresden-Friedrichstadt (km 0,0) - StrUeb_6241_6244 (km 0,8)

Streckennummer 6241
StrUeb_6241_6244 (km 63,9) - Dresden Freiberger Straße (km 63,8)

[Streckennummer 6240
Dresden Hbf (km 62,4) - Dresden Freiberger Straße  (km 63,8)]
