### ISSUE TITLE
Berlin-Spandau <-> Hamburg Hbf via Büchen

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#34]
Streckennummer 6100
Berlin-Spandau (km 12,4) - Hamburg Hbf (km 286,6)

**Comment by christophstoeber** [comment]
Streckennummer 6107
Berlin Hauptbahnhof - Lehrter Bahnhof (km 1,3) - Berlin-Spandau (km 10,3)

Streckennummer 6100
Berlin-Spandau (km 12,4) - Hamburg Hbf (km 286,6)
