### ISSUE TITLE
Bremen Hbf <-> Hamburg Hbf via Rotenburg und Buchholz (Nordheide) <-> Hamburg-Harburg via Maschen

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#35]
Streckennummer 2200
Bremen Hbf (km 239,7) - Hamburg Hbf (km 355,3)

Strecke von Hamburg-Harburg nach Buchholz (Nordheide) über Maschen
Streckennummer 1280
Hamburg-Harburg (km 29,4) - Buchholz (Nordheide) (km 0,0)

**Comment by christophstoeber** [comment]
Streckennummer 2200
Bremen Hbf (km 239,7) - Hamburg Hbf (km 355,3)
