### ISSUE TITLE
Hamburg Hbf <-> Hannover Hbf via Uelzen

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#39]
[Streckennummer 2200
Hamburg Hbf (km 355,3) - Hamburg-Harburg (km 343,3)]

Streckennummer 1720
Hamburg-Harburg (km 169,4) - Celle (km 44,1)

Streckennummer 1710
Celle (km 40,816) - Hannover Hbf (km 0,0)

**Comment by christophstoeber** [comment]
Streckennummer 2200
Hamburg Hbf (km 355,3) - Hamburg-Harburg (km 343,3)

Streckennummer 1720
Hamburg-Harburg (km 169,4) - Celle (km 44,1)

Streckennummer 1710
Celle (km 40,816) - Hannover Hbf (km 0,0)
