### ISSUE TITLE
Rathenow<-> Uelzen via Stendal (für Berlin Ostbahnhof <-> Hamburg Hbf via Uelzen)

### ISSUE THREAD

**Issue by ChristophsAcc** [ChristophsAcc/Fahrzeitrechner#5]
Rathenow

Streckennummer 6899
Stendal Hbf (km 0,0) - Uelzen (km 107,5)

**Comment by christophstoeber** [comment]
Streckennummer 6107
Berlin Hbf (km 0,0) - Ribbeck (km 48,9)

Streckennummer 6185
Ribbeck (km 148,5) - Bamme (km 165,6)

Streckennummer 6107
Bamme (km  65,6) - Stendal Hbf (km 105,1)

Streckennummer 6899
Stendal Hbf (km 0,0) - Uelzen (km 107,5)

Streckennummer 1720
Uelzen (km 96,4) - Hamburg-Harburg (169,4)

Streckennummer 2200
Hamburg-Harburg (km 343,3) - Hamburg Hbf (km 355,3)
